//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj28102018.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_NavMenus
    {
        public int NavID { get; set; }
        public string NavName { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string NavUrl { get; set; }
    }
}
